### ISSUE TITLE
Synchronize colormaps

### ISSUE THREAD

**Issue by tlecomte** [Icy-imaging/Icy-Kernel#412] opened 2012-09-25 08:11 UTC
I miss the feature to "synchronize" colormaps, or more precisely synchronize component bounds between sequences. The goal is to visually compare the absolute intensities of two sequences. As for the interface, I was thinking of something like the padlock used to synchronize the canvas of several sequences.

**Comment by Stephane-D** [comment] 2016-06-01 08:51
Duplicate of https://github.com/Icy-imaging/Icy-Kernel/issues/288

**Closed by Stephane-D** 2016-06-01 08:51 UTC
Labels: feature request
